### ISSUE TITLE
Skipfish problems

### ISSUE THREAD

**Issue by esotracuenta** [owtf/ptp#6] opened 2014-10-21 01:56 UTC
Hello, when i use the tool i get this error:

Traceback (most recent call last):
  File "i.py", line 6, in <module>
    ptp.parse('/home/ml/02/propios/skipfish/5874/unix2/')
  File "/root/PTP-0.2.0/ptp/ptp.py", line 120, in parse
    self.vulns = self.parser.parse_report()
  File "/root/PTP-0.2.0/ptp/tools/skipfish/parser.py", line 177, in parse_report
    for vuln in ast.literal_eval(report[REPORT_VAR_NAME])]
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 834
    { 'url': 'http://congeladostiendadelsol.com/icons/small/?C=9876sfi
                                                                     ^
SyntaxError: EOL while scanning string literal

im using this source code:

------

from __future__ import print_function
from ptp import PTP

if __name__ == '__main__':
	ptp = PTP()
        ptp.parse('/home/ml/02/propios/skipfish/5874/unix2/')
        print('Highest severity:', ptp.get_highest_ranking())

-0------

Tnx!

**Comment by DePierre** [comment] 2016-05-23 09:00
Not able to reproduce the bug. Closing for now until able to reproduce it.

**Closed by DePierre** 2016-05-23 09:00 UTC
Labels: bug, need more info
